FROM ghcr.io/astral-sh/uv:python3.13-bookworm

RUN useradd -ms /bin/sh -u 1001 app
USER app

WORKDIR /app
COPY --chown=app:app . .

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    ENV=production

RUN uv sync --locked

EXPOSE 5000

ENTRYPOINT [ "sh", "-c", \
    ".venv/bin/python -Xfrozen_modules=off -m uvicorn main:app --host 0.0.0.0 --port 5000" \
    ]
