FROM node:22

RUN useradd -ms /bin/sh -u 1001 app
USER app

WORKDIR /app
COPY --chown=app:app . .

ENV ENV=production

RUN npm install --force

RUN npm run build

EXPOSE 3000

ENTRYPOINT [ "sh", "-c", \
    "npm start" \
    ]
