FROM oven/bun:1

RUN useradd -ms /bin/sh -u 1001 app
USER app

WORKDIR /app
COPY --chown=app:app . .

ENV ENV=development

USER root

EXPOSE 3000

ENTRYPOINT [ "sh", "-c", \
    "bun install --force && bun run dev" \
    ]
