FROM oven/bun:1

RUN useradd -ms /bin/sh -u 1001 app
USER app

WORKDIR /app
COPY --chown=app:app . .

ENV ENV=production

RUN bun install --production

RUN bun run build

EXPOSE 3000

ENTRYPOINT [ "sh", "-c", \
    "bun start" \
    ]
